"use client";

import { type FormEvent, useCallback, useEffect, useState } from "react";
import { Alert, Box, Button, Group, Select, Table, Text, TextInput, Title } from "@mantine/core";
import { LoaderCircle, Trash2, UserPlus } from "lucide-react";
import { withBasePath } from "@/lib/base-path";
import type { AuthorizedProjectSummary } from "@/lib/auth/ui-types";
import { ProjectContextHeader } from "./ProjectContextHeader";

type Member = { id: string; userId: string; role: "project_manager" | "project_member" | "viewer"; displayName: string; email: string };
const roleLabels: Record<Member["role"], string> = { project_manager: "项目经理", project_member: "项目成员", viewer: "只读成员" };
const roleOptions = Object.entries(roleLabels).map(([value, label]) => ({ value, label }));

export function ProjectMembersPage({ project }: { project: AuthorizedProjectSummary }) {
  const [members, setMembers] = useState<Member[]>([]); const [email, setEmail] = useState(""); const [role, setRole] = useState<Member["role"]>("project_member"); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { const response = await fetch(withBasePath(`/api/projects/${project.id}/members`), { credentials: "include", cache: "no-store" }); const body = await response.json() as { members?: Member[]; error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? "成员列表加载失败"); setMembers(body.members ?? []); }, [project.id]);
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((caught) => setError(caught instanceof Error ? caught.message : "成员列表加载失败")); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const add = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(null); try { const response = await fetch(withBasePath(`/api/projects/${project.id}/members`), { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, role }) }); const body = await response.json() as { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? "添加失败"); setEmail(""); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "添加失败"); } finally { setBusy(false); } };
  const update = async (member: Member, nextRole: Member["role"]) => { setError(null); const response = await fetch(withBasePath(`/api/projects/${project.id}/members/${member.id}`), { method: "PATCH", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ role: nextRole }) }); if (!response.ok) { const body = await response.json() as { error?: { message?: string } }; setError(body.error?.message ?? "角色更新失败"); return; } await load(); };
  const remove = async (member: Member) => { if (!window.confirm(`确认移除 ${member.displayName}？`)) return; const response = await fetch(withBasePath(`/api/projects/${project.id}/members/${member.id}`), { method: "DELETE", credentials: "include" }); if (!response.ok) { const body = await response.json() as { error?: { message?: string } }; setError(body.error?.message ?? "移除失败"); return; } await load(); };
  return <div className="min-h-full"><ProjectContextHeader project={project} activeTab="members" /><Box px={{ base: "md", sm: "lg" }} py="xl"><Title order={3}>成员与权限</Title><Text size="sm" c="dimmed" mt={5}>成员关系和写入权限由服务端统一校验。</Text>{project.permissions.canManageMembers ? <form onSubmit={add}><Group mt="lg" align="end"><TextInput required type="email" label="成员邮箱" value={email} onChange={(event) => setEmail(event.currentTarget.value)} placeholder="成员邮箱" miw={260} style={{ flex: 1 }} /><Select label="角色" value={role} onChange={(value) => setRole((value ?? "project_member") as Member["role"])} data={roleOptions} w={160} /><Button type="submit" loading={busy} leftSection={busy ? <LoaderCircle size={16} /> : <UserPlus size={16} />}>添加成员</Button></Group></form> : null}{error ? <Alert color="red" title="操作未完成" mt="md">{error}</Alert> : null}<Box mt="lg" bd="1px solid var(--mantine-color-gray-3)" bg="white" style={{ borderRadius: "var(--mantine-radius-md)", overflow: "hidden" }}><Table.ScrollContainer minWidth={620}><Table highlightOnHover><Table.Thead><Table.Tr><Table.Th>成员</Table.Th><Table.Th>邮箱</Table.Th><Table.Th>角色</Table.Th>{project.permissions.canManageMembers ? <Table.Th><span className="sr-only">操作</span></Table.Th> : null}</Table.Tr></Table.Thead><Table.Tbody>{members.map((member) => <Table.Tr key={member.id}><Table.Td fw={600}>{member.displayName}</Table.Td><Table.Td><Text size="sm" c="dimmed">{member.email}</Text></Table.Td><Table.Td>{project.permissions.canManageMembers ? <Select value={member.role} onChange={(value) => value && void update(member, value as Member["role"])} data={roleOptions} w={150} /> : roleLabels[member.role]}</Table.Td>{project.permissions.canManageMembers ? <Table.Td><Button variant="subtle" color="red" size="compact-sm" onClick={() => void remove(member)} aria-label={`移除 ${member.displayName}`}><Trash2 size={16} /></Button></Table.Td> : null}</Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer></Box></Box></div>;
}
