"use client";

import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, Download, FileText, LoaderCircle, Save, Sparkles } from "lucide-react";
import { withBasePath } from "@/lib/base-path";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

type Item = { id: string; label: string; status: string; value: string; citationLabels: string[] };
type Question = { id: string; group: string; prompt: string; required: boolean; answer: string; status: "pending" | "answered" | "not_applicable"; citationLabels: string[] };
type Overview = { id: string; versionNumber: number; status: "prefilled" | "needs_confirmation" | "ready" | "generated" | "failed"; items: Item[]; questions: Question[]; markdown: string; failureCode: string | null; savedDocumentId: string | null; citations: { label: string; displayName: string; sourceScope: string; excerpt: string }[] };

const labels: Record<string, string> = { confirmed: "已确认", user_confirmed: "已确认", inferred: "AI 推断", missing: "缺失", conflict: "存在冲突", not_applicable: "不适用" };

export function RequirementOverviewWorkspace({ projectId }: { projectId: string }) {
  const [overview, setOverview] = useState<Overview | null>(null);
  const [busy, setBusy] = useState<"prefill" | "save" | "generate" | "artifact" | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loaded, setLoaded] = useState(false);
  const request = async (path: string, init?: RequestInit) => {
    const response = await fetch(withBasePath(path), { credentials: "include", ...init });
    const body = await response.json() as { overview?: Overview; overviews?: Overview[]; error?: { message?: string } };
    if (!response.ok) throw new Error(body.error?.message ?? "操作未完成");
    return body;
  };
  const load = useCallback(async () => { const result = await request(`/api/projects/${projectId}/requirement-overviews`); setOverview(result.overviews?.[0] ?? null); setLoaded(true); }, [projectId]);
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((caught) => { setError(caught instanceof Error ? caught.message : "需求概览加载失败"); setLoaded(true); }); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const create = async () => { setBusy("prefill"); setError(null); try { const result = await request(`/api/projects/${projectId}/requirement-overviews`, { method: "POST", headers: { "content-type": "application/json" }, body: "{}" }); setOverview(result.overview ?? null); } catch (caught) { setError(caught instanceof Error ? caught.message : "无法建立需求概览"); } finally { setBusy(null); } };
  const saveAnswers = async () => { if (!overview) return; setBusy("save"); setError(null); try { const result = await request(`/api/projects/${projectId}/requirement-overviews/${overview.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ answers: overview.questions.map(({ id, answer, status }) => ({ id, answer, notApplicable: status === "not_applicable" })) }) }); setOverview(result.overview ?? null); } catch (caught) { setError(caught instanceof Error ? caught.message : "保存失败"); } finally { setBusy(null); } };
  const generate = async () => { if (!overview) return; setBusy("generate"); setError(null); try { const result = await request(`/api/projects/${projectId}/requirement-overviews/${overview.id}/generate`, { method: "POST", headers: { "content-type": "application/json" }, body: "{}" }); setOverview(result.overview ?? null); } catch (caught) { setError(caught instanceof Error ? caught.message : "生成失败"); await load().catch(() => undefined); } finally { setBusy(null); } };
  const saveToProject = async () => { if (!overview) return; setBusy("artifact"); setError(null); try { const result = await request(`/api/projects/${projectId}/requirement-overviews/${overview.id}/save`, { method: "POST", headers: { "content-type": "application/json" }, body: "{}" }); setOverview(result.overview ?? null); } catch (caught) { setError(caught instanceof Error ? caught.message : "保存到项目失败"); } finally { setBusy(null); } };
  if (!loaded) return <div className="border-t p-4 text-xs text-muted-foreground"><LoaderCircle className="mr-2 inline size-3 animate-spin" />正在加载需求概览</div>;
  if (!overview) return <section className="border-t bg-muted/10 px-4 py-5" data-testid="requirement-overview-empty"><div className="rounded-lg border bg-card p-4"><h4 className="text-sm font-semibold">需求概览</h4><p className="mt-1 text-xs leading-5 text-muted-foreground">先从当前项目的有效资料预填事实、范围与资料缺口，再由项目经理集中确认。</p><Button className="mt-3" size="sm" disabled={busy === "prefill"} onClick={() => void create()}>{busy === "prefill" ? <LoaderCircle className="animate-spin" /> : <Sparkles />}开始需求概览</Button>{error ? <p className="mt-2 text-xs text-destructive">{error}</p> : null}</div></section>;
  return <section className="border-t bg-muted/10 px-4 py-5" data-testid="requirement-overview-workspace">
    <div className="mx-auto max-w-3xl rounded-lg border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h4 className="text-sm font-semibold">需求概览 v{overview.versionNumber}</h4><Badge variant="outline">{{ prefilled: "资料已预填", needs_confirmation: "等待确认", ready: "可生成", generated: "已生成", failed: "生成失败" }[overview.status]}</Badge></div><p className="mt-1 text-xs text-muted-foreground">来源、AI 推断与待确认项已分别标注；不会把资料不足当作错误。</p></div>{overview.status === "generated" ? <a className="inline-flex h-8 items-center gap-1.5 rounded-lg border px-3 text-xs font-medium hover:bg-muted" href={withBasePath(`/api/projects/${projectId}/requirement-overviews/${overview.id}/export`)}><Download className="size-3.5" />下载 Markdown</a> : null}</div>
      {error ? <Alert variant="destructive" className="mt-4"><AlertTitle>{overview.status === "failed" ? "AI 服务暂时不可用" : "操作未完成"}</AlertTitle><AlertDescription>{error}</AlertDescription></Alert> : null}
      <div className="mt-5 grid gap-3 sm:grid-cols-2">{overview.items.map((item) => <div key={item.id} className="rounded-lg border p-3"><div className="flex items-center justify-between gap-2"><p className="text-xs font-medium">{item.label}</p><Badge variant="outline" className="text-[10px]">{labels[item.status] ?? item.status}</Badge></div><p className="mt-2 text-xs leading-5 text-muted-foreground">{item.value}</p>{item.citationLabels.length ? <p className="mt-2 text-[10px] text-primary">来源：{item.citationLabels.map((label) => `[${label}]`).join(" ")}</p> : null}</div>)}</div>
      {overview.status !== "generated" ? <div className="mt-5 space-y-4 border-t pt-5"><div><h5 className="text-sm font-semibold">请集中确认</h5><p className="mt-1 text-xs text-muted-foreground">必填问题完成后才会生成固定格式的需求概览。</p></div>{overview.questions.map((question) => <div key={question.id} className="rounded-lg border p-3"><div className="flex items-start justify-between gap-2"><p className="text-xs font-medium">{question.group}{question.required ? <span className="ml-1 text-destructive">*</span> : null}</p><Button type="button" size="sm" variant="ghost" onClick={() => setOverview((current) => current ? { ...current, questions: current.questions.map((entry) => entry.id === question.id ? { ...entry, status: entry.status === "not_applicable" ? "pending" : "not_applicable", answer: entry.status === "not_applicable" ? entry.answer : "" } : entry) } : current)}>{question.status === "not_applicable" ? "恢复填写" : "不适用"}</Button></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{question.prompt}</p><Textarea className="mt-3" rows={2} disabled={question.status === "not_applicable"} value={question.answer} onChange={(event) => setOverview((current) => current ? { ...current, questions: current.questions.map((entry) => entry.id === question.id ? { ...entry, answer: event.target.value, status: event.target.value.trim() ? "answered" : "pending" } : entry) } : current)} placeholder="由项目经理确认，或标记为不适用" /></div>)}</div> : <div className="mt-5 border-t pt-5"><pre className="max-h-80 overflow-auto whitespace-pre-wrap text-xs leading-6 text-foreground">{overview.markdown}</pre></div>}
      <div className="mt-5 flex flex-wrap gap-2 border-t pt-4">{overview.status !== "generated" ? <><Button variant="outline" size="sm" disabled={busy === "save"} onClick={() => void saveAnswers()}>{busy === "save" ? <LoaderCircle className="animate-spin" /> : <CheckCircle2 />}保存确认</Button><Button size="sm" disabled={overview.status !== "ready" || busy === "generate"} onClick={() => void generate()}>{busy === "generate" ? <LoaderCircle className="animate-spin" /> : <FileText />}生成需求概览</Button></> : <Button size="sm" disabled={Boolean(overview.savedDocumentId) || busy === "artifact"} onClick={() => void saveToProject()}>{busy === "artifact" ? <LoaderCircle className="animate-spin" /> : <Save />}{overview.savedDocumentId ? "已保存到项目" : "保存到项目"}</Button>}</div>
      {overview.citations.length ? <div className="mt-4 border-t pt-4"><p className="text-xs font-semibold">引用</p>{overview.citations.map((citation) => <p key={citation.label} className="mt-1 text-[11px] text-muted-foreground">[{citation.label}] [{citation.sourceScope === "organization" ? "常规模板" : "项目资料"}] {citation.displayName}</p>)}</div> : null}
    </div>
  </section>;
}
