"use client";
import { useCallback, useEffect, useState } from "react";
import { Database, KeyRound, Plus, RefreshCw, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { withBasePath } from "@/lib/base-path";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Snapshot = { providers: Array<{ id: string; name: string; providerType: string; region: string; enabled: boolean; lastTestStatus: string; secretReference: string; hasServerSecret: boolean }>; generationModels: Array<{ id: string; displayName: string; modelId: string; providerProfileId: string; enabled: boolean; supportsJson: boolean; lastTestStatus: string }>; embeddingModels: Array<{ id: string; displayName: string; modelId: string; providerProfileId: string; dimensions: number; enabled: boolean; lastTestStatus: string }>; scenarios: Array<{ id: string; scenario: string; generationModelId: string | null; embeddingModelId: string | null; enabled: boolean }>; vectorDimensions: number };
const names: Record<string, string> = { general_chat: "通用对话", project_grounded_chat: "项目知识问答", requirement_overview_prefill: "需求概览预填", requirement_overview_guidance: "需求概览引导", requirement_markdown_generation: "需求概览 Markdown 生成" };

export function AiModelManagementPage({ organizationId, verificationProjectId }: { organizationId: string; verificationProjectId: string | null }) {
  const [data, setData] = useState<Snapshot | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [provider, setProvider] = useState({ name: "", type: "dashscope", url: "https://dashscope.aliyuncs.com/compatible-mode/v1", region: "cn-beijing", secret: "QWEN_API_KEY_FILE" }); const [model, setModel] = useState({ name: "", modelId: "", providerId: "" }); const [embedding, setEmbedding] = useState({ name: "", modelId: "", providerId: "" });
  const load = useCallback(async () => { const response = await fetch(withBasePath(`/api/admin/ai-configuration?organizationId=${encodeURIComponent(organizationId)}`), { credentials: "include", cache: "no-store" }); const body = await response.json() as Snapshot & { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? "AI 配置加载失败"); setData(body); }, [organizationId]);
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((caught) => setError(caught instanceof Error ? caught.message : "AI 配置加载失败")); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const mutate = async (payload: Record<string, unknown>) => { setBusy(true); setError(null); try { const response = await fetch(withBasePath("/api/admin/ai-configuration"), { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...payload, organizationId }) }); const body = await response.json() as Snapshot & { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? "配置未保存"); setData(body); } catch (caught) { setError(caught instanceof Error ? caught.message : "配置未保存"); } finally { setBusy(false); } };
  if (!data) return <div className="p-6 text-sm text-muted-foreground">正在加载 AI 配置…</div>;
  return <div className="mx-auto max-w-6xl space-y-6"><header><p className="text-xs font-medium text-primary">管理员设置</p><h1 className="mt-1 text-xl font-semibold">Provider 与模型管理</h1><p className="mt-2 text-sm text-muted-foreground">凭据仅保留服务器 Secret 引用，浏览器不会显示、提交或保存 API Key。</p></header>{error ? <Alert variant="destructive"><AlertTitle>操作未完成</AlertTitle><AlertDescription>{error}</AlertDescription></Alert> : null}
    <section className="rounded-lg border bg-card p-5"><div className="flex items-center gap-2"><KeyRound className="size-4 text-primary" /><h2 className="text-sm font-semibold">Provider</h2></div><div className="mt-4 grid gap-3 md:grid-cols-4"><Input value={provider.name} onChange={(e) => setProvider({ ...provider, name: e.target.value })} placeholder="Provider 名称" /><Select value={provider.type} onValueChange={(type) => setProvider({ ...provider, type })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="dashscope">DashScope</SelectItem><SelectItem value="openai_compatible">OpenAI Compatible</SelectItem></SelectContent></Select><Input value={provider.url} onChange={(e) => setProvider({ ...provider, url: e.target.value })} placeholder="HTTPS Base URL" /><Button disabled={busy || !provider.name.trim()} onClick={() => void mutate({ action: "create_provider", name: provider.name, providerType: provider.type, baseUrl: provider.url, region: provider.region, secretReference: provider.secret })}><Plus />添加 Provider</Button></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-muted-foreground"><tr><th className="py-2">名称</th><th>类型</th><th>区域</th><th>服务器凭据</th><th>测试</th></tr></thead><tbody>{data.providers.map((item) => <tr key={item.id} className="border-t"><td className="py-3 font-medium">{item.name}</td><td>{item.providerType}</td><td>{item.region}</td><td><Badge variant="outline">{item.hasServerSecret ? "已配置引用" : "等待服务器配置"}</Badge></td><td>{item.lastTestStatus}</td></tr>)}</tbody></table></div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-lg border bg-card p-5"><div className="flex items-center gap-2"><SlidersHorizontal className="size-4 text-primary" /><h2 className="text-sm font-semibold">文本模型</h2></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><Input value={model.name} onChange={(e) => setModel({ ...model, name: e.target.value })} placeholder="显示名称" /><Input value={model.modelId} onChange={(e) => setModel({ ...model, modelId: e.target.value })} placeholder="模型 ID" /><Select value={model.providerId} onValueChange={(providerId) => setModel({ ...model, providerId })}><SelectTrigger><SelectValue placeholder="Provider" /></SelectTrigger><SelectContent>{data.providers.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div><Button className="mt-3" size="sm" disabled={busy || !model.name || !model.modelId || !model.providerId} onClick={() => void mutate({ action: "create_generation_model", displayName: model.name, modelId: model.modelId, providerProfileId: model.providerId, supportsJson: true })}><Plus />添加文本模型</Button><div className="mt-4 space-y-2">{data.generationModels.map((item) => <div key={item.id} className="flex items-center justify-between rounded border p-3 text-xs"><span><b>{item.displayName}</b><span className="ml-2 text-muted-foreground">{item.modelId}</span></span><div className="flex gap-2"><Badge variant="outline">{item.lastTestStatus}</Badge><Badge variant="outline">{item.enabled ? "已启用" : "未启用"}</Badge>{verificationProjectId ? <Button size="sm" variant="outline" disabled={busy} onClick={() => void mutate({ action: "test_generation_model", projectId: verificationProjectId, modelId: item.id })}><RefreshCw />测试</Button> : null}<Button size="sm" variant="outline" disabled={busy || (!item.enabled && item.lastTestStatus !== "passed")} onClick={() => void mutate({ action: "set_generation_model_enabled", modelId: item.id, enabled: !item.enabled })}>{item.enabled ? "停用" : "启用"}</Button></div></div>)}</div></div>
      <div className="rounded-lg border bg-card p-5"><div className="flex items-center gap-2"><Database className="size-4 text-primary" /><h2 className="text-sm font-semibold">向量模型</h2></div><p className="mt-2 text-xs leading-5 text-muted-foreground">当前 pgvector 字段为 {data.vectorDimensions} 维。只有 {data.vectorDimensions} 维模型可以绑定，禁止混用不同维度向量。</p><div className="mt-4 grid gap-2 sm:grid-cols-3"><Input value={embedding.name} onChange={(e) => setEmbedding({ ...embedding, name: e.target.value })} placeholder="显示名称" /><Input value={embedding.modelId} onChange={(e) => setEmbedding({ ...embedding, modelId: e.target.value })} placeholder="模型 ID" /><Select value={embedding.providerId} onValueChange={(providerId) => setEmbedding({ ...embedding, providerId })}><SelectTrigger><SelectValue placeholder="Provider" /></SelectTrigger><SelectContent>{data.providers.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div><Button className="mt-3" size="sm" variant="outline" disabled={busy || !embedding.name || !embedding.modelId || !embedding.providerId} onClick={() => void mutate({ action: "create_embedding_model", displayName: embedding.name, modelId: embedding.modelId, providerProfileId: embedding.providerId, dimensions: 1024 })}><Plus />添加 1024 维向量模型</Button><div className="mt-4 space-y-2">{data.embeddingModels.map((item) => <div key={item.id} className="flex items-center justify-between rounded border p-3 text-xs"><span><b>{item.displayName}</b><span className="ml-2 text-muted-foreground">{item.modelId} · {item.dimensions} 维</span></span><div className="flex gap-2"><Badge variant="outline">{item.lastTestStatus}</Badge>{verificationProjectId ? <Button size="sm" variant="outline" disabled={busy} onClick={() => void mutate({ action: "test_embedding_model", projectId: verificationProjectId, modelId: item.id })}><RefreshCw />测试</Button> : null}</div></div>)}</div></div></section>
    <section className="rounded-lg border bg-card p-5"><div className="flex items-center gap-2"><ShieldCheck className="size-4 text-primary" /><h2 className="text-sm font-semibold">场景绑定</h2></div><p className="mt-1 text-xs text-muted-foreground">业务页面只使用场景，不暴露 Provider、Prompt 或密钥。绑定前应先完成连接测试。</p><div className="mt-4 space-y-2">{data.scenarios.map((item) => <div key={item.id} className="grid gap-2 rounded border p-3 md:grid-cols-[180px_1fr_1fr_auto]"><span className="self-center text-xs font-medium">{names[item.scenario] ?? item.scenario}</span><Select value={item.generationModelId ?? "none"} onValueChange={(generationModelId) => void mutate({ action: "bind_scenario", scenario: item.scenario, generationModelId: generationModelId === "none" ? null : generationModelId, embeddingModelId: item.embeddingModelId, enabled: item.enabled })}><SelectTrigger><SelectValue placeholder="文本模型" /></SelectTrigger><SelectContent><SelectItem value="none">不使用文本模型</SelectItem>{data.generationModels.map((model) => <SelectItem key={model.id} value={model.id}>{model.displayName}</SelectItem>)}</SelectContent></Select><Select value={item.embeddingModelId ?? "none"} onValueChange={(embeddingModelId) => void mutate({ action: "bind_scenario", scenario: item.scenario, generationModelId: item.generationModelId, embeddingModelId: embeddingModelId === "none" ? null : embeddingModelId, enabled: item.enabled })}><SelectTrigger><SelectValue placeholder="向量模型" /></SelectTrigger><SelectContent><SelectItem value="none">不使用向量模型</SelectItem>{data.embeddingModels.map((model) => <SelectItem key={model.id} value={model.id}>{model.displayName} · {model.dimensions}维</SelectItem>)}</SelectContent></Select><Badge variant="outline">{item.enabled ? "已启用" : "停用"}</Badge></div>)}</div></section>
  </div>;
}
