"use client";

import { useMemo, useState } from "react";
import { BookOpenCheck, Building2, FileSearch, FolderArchive, Search, ShieldCheck } from "lucide-react";
import { Badge, PageHeader } from "@/components/common";

const assets = [
  { name: "项目交付治理手册 2026", type: "公司规则", owner: "项目管理办公室", count: 48, updated: "今天", status: "当前有效" },
  { name: "客户需求澄清清单", type: "标准模板", owner: "项目管理办公室", count: 22, updated: "昨天", status: "当前有效" },
  { name: "零售互动项目案例库", type: "历史案例", owner: "体验创新中心", count: 36, updated: "7 月 8 日", status: "已确认" },
  { name: "Scope 变更评审规则", type: "公司规则", owner: "交付质量组", count: 17, updated: "7 月 3 日", status: "当前有效" },
  { name: "海外项目合规要求", type: "领域知识", owner: "法务与合规", count: 29, updated: "6 月 28 日", status: "待更新" },
];
export function GlobalKnowledgePage() { const [query, setQuery] = useState(""); const filtered = useMemo(() => assets.filter((item) => item.name.includes(query) || item.type.includes(query)), [query]); return <div className="space-y-6"><PageHeader eyebrow="Knowledge & Assets" title="知识与资产" description="跨项目复用已确认规则、标准模板与历史案例；项目私有知识仍受项目权限和版本过滤控制。" />
  <div className="grid gap-3 md:grid-cols-3"><div className="app-card flex items-center gap-3 p-4"><span className="grid size-10 place-items-center rounded-xl bg-primary/8 text-primary"><BookOpenCheck className="size-5" /></span><div><strong className="text-lg">152</strong><p className="text-xs text-muted-foreground">已确认知识条目</p></div></div><div className="app-card flex items-center gap-3 p-4"><span className="grid size-10 place-items-center rounded-xl bg-success-soft text-success"><FolderArchive className="size-5" /></span><div><strong className="text-lg">18</strong><p className="text-xs text-muted-foreground">历史项目案例</p></div></div><div className="app-card flex items-center gap-3 p-4"><span className="grid size-10 place-items-center rounded-xl bg-warning-soft text-warning"><ShieldCheck className="size-5" /></span><div><strong className="text-lg">96.8%</strong><p className="text-xs text-muted-foreground">有效版本覆盖率</p></div></div></div>
  <section className="app-card overflow-hidden"><div className="flex flex-col gap-3 border-b bg-surface/60 p-4 sm:flex-row sm:items-center"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索公司规则、模板或历史案例" className="h-10 w-full rounded-lg border bg-card pl-9 pr-3 text-sm" /></label><Badge tone="primary"><FileSearch className="mr-1 size-3" />Hybrid Search 已预留</Badge></div><div className="divide-y">{filtered.map((item) => <button key={item.name} className="grid w-full grid-cols-[1fr_auto] gap-4 px-5 py-4 text-left transition-colors hover:bg-surface sm:grid-cols-[minmax(240px,1.4fr)_150px_160px_90px_100px]"><div className="flex min-w-0 items-center gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-muted text-muted-foreground"><Building2 className="size-4" /></span><strong className="truncate text-xs font-medium">{item.name}</strong></div><span className="text-xs text-muted-foreground">{item.type}</span><span className="hidden text-xs text-muted-foreground sm:block">{item.owner}</span><span className="hidden text-xs text-muted-foreground sm:block">{item.count} 条</span><Badge tone={item.status === "待更新" ? "warning" : "success"}>{item.status}</Badge></button>)}</div></section></div>; }
