"use client";
/* eslint-disable react-hooks/incompatible-library -- TanStack Table exposes stable imperative helpers that React Compiler intentionally skips. */

import { flexRender, getCoreRowModel, getPaginationRowModel, getSortedRowModel, useReactTable, type ColumnDef, type SortingState } from "@tanstack/react-table";
import { ArrowDown, ArrowUp, ArrowUpDown, ChevronLeft, ChevronRight } from "lucide-react";
import { useState } from "react";
import { Button } from "./button";
import { EmptyState } from "./state-showcase";

export function DataTable<TData>({ data, columns, onRowClick, pageSize = 8 }: { data: TData[]; columns: ColumnDef<TData>[]; onRowClick?: (row: TData) => void; pageSize?: number }) {
  const [sorting, setSorting] = useState<SortingState>([]);
  const table = useReactTable({ data, columns, state: { sorting }, onSortingChange: setSorting, getCoreRowModel: getCoreRowModel(), getSortedRowModel: getSortedRowModel(), getPaginationRowModel: getPaginationRowModel(), initialState: { pagination: { pageSize } } });
  return <div className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="border-b bg-surface"><tr>{table.getHeaderGroups()[0]?.headers.map((header) => <th key={header.id} className="px-3 py-2.5 text-[11px] font-semibold text-muted-foreground">{header.isPlaceholder ? null : <button className="inline-flex items-center gap-1 hover:text-foreground" onClick={header.column.getToggleSortingHandler()} disabled={!header.column.getCanSort()}>{flexRender(header.column.columnDef.header, header.getContext())}{header.column.getCanSort() ? header.column.getIsSorted() === "asc" ? <ArrowUp className="size-3" /> : header.column.getIsSorted() === "desc" ? <ArrowDown className="size-3" /> : <ArrowUpDown className="size-3 opacity-40" /> : null}</button>}</th>)}</tr></thead><tbody className="divide-y">{table.getRowModel().rows.map((row) => <tr key={row.id} tabIndex={onRowClick ? 0 : undefined} onClick={() => onRowClick?.(row.original)} onKeyDown={(event) => { if (onRowClick && (event.key === "Enter" || event.key === " ")) onRowClick(row.original); }} className={onRowClick ? "transition-colors hover:bg-primary/[0.035] focus:bg-primary/[0.05]" : undefined}>{row.getVisibleCells().map((cell) => <td key={cell.id} className="px-3 py-3 text-xs text-foreground">{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</tr>)}</tbody></table>{data.length === 0 ? <EmptyState /> : null}</div>{table.getPageCount() > 1 ? <div className="flex items-center justify-between border-t px-3 py-2.5 text-xs text-muted-foreground"><span>第 {table.getState().pagination.pageIndex + 1} / {table.getPageCount()} 页 · 共 {data.length} 条</span><div className="flex gap-1"><Button size="icon" variant="ghost" className="size-7" onClick={() => table.previousPage()} disabled={!table.getCanPreviousPage()} aria-label="上一页"><ChevronLeft className="size-3.5" /></Button><Button size="icon" variant="ghost" className="size-7" onClick={() => table.nextPage()} disabled={!table.getCanNextPage()} aria-label="下一页"><ChevronRight className="size-3.5" /></Button></div></div> : null}</div>;
}
