import {
  bigint,
  boolean,
  check,
  foreignKey,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  unique,
  uniqueIndex,
  varchar,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { documentStatusEnum, documentStorageStatusEnum } from "./enums";
import { project } from "./projects";
import { user } from "./users";

/**
 * A logical document. Objects are deliberately not deleted when a document is
 * archived, and project deletion is restricted while file metadata exists.
 */
export const projectDocument = pgTable(
  "project_documents",
  {
    id: text("id").primaryKey(),
    projectId: text("project_id")
      .notNull()
      .references(() => project.id, { onDelete: "restrict" }),
    displayName: varchar("display_name", { length: 240 }).notNull(),
    status: documentStatusEnum("document_status").notNull().default("pending"),
    createdBy: text("created_by")
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    archivedBy: text("archived_by").references(() => user.id, {
      onDelete: "restrict",
    }),
    archivedAt: timestamp("archived_at", { withTimezone: true, mode: "date" }),
  },
  (table) => [
    index("project_documents_project_status_idx").on(
      table.projectId,
      table.status,
      table.updatedAt,
    ),
    index("project_documents_created_by_idx").on(table.createdBy),
    unique("project_documents_id_project_unique").on(table.id, table.projectId),
    check(
      "project_documents_display_name_nonempty",
      sql`length(btrim(${table.displayName})) > 0`,
    ),
    check(
      "project_documents_archive_state_check",
      sql`(
        ${table.status} = 'archived'
        and ${table.archivedBy} is not null
        and ${table.archivedAt} is not null
      ) or (
        ${table.status} <> 'archived'
        and ${table.archivedBy} is null
        and ${table.archivedAt} is null
      )`,
    ),
  ],
);

/**
 * An immutable object-backed version. originalFilename is response metadata;
 * objectKey is always generated by the server and never serialized to clients.
 */
export const projectDocumentVersion = pgTable(
  "project_document_versions",
  {
    id: text("id").primaryKey(),
    documentId: text("document_id").notNull(),
    projectId: text("project_id")
      .notNull()
      .references(() => project.id, { onDelete: "restrict" }),
    versionNumber: integer("version_number").notNull(),
    isCurrent: boolean("is_current").notNull().default(false),
    uploadId: varchar("upload_id", { length: 128 }).notNull(),
    objectKey: varchar("object_key", { length: 700 }).notNull(),
    originalFilename: varchar("original_filename", { length: 255 }).notNull(),
    normalizedExtension: varchar("normalized_extension", { length: 12 }).notNull(),
    declaredMimeType: varchar("declared_mime_type", { length: 200 }).notNull(),
    detectedMimeType: varchar("detected_mime_type", { length: 200 }).notNull(),
    sizeBytes: bigint("size_bytes", { mode: "number" }).notNull(),
    sha256: varchar("sha256", { length: 64 }).notNull(),
    storageEtag: varchar("storage_etag", { length: 200 }),
    storageStatus: documentStorageStatusEnum("storage_status")
      .notNull()
      .default("pending"),
    failureCode: varchar("failure_code", { length: 64 }),
    uploadedBy: text("uploaded_by")
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    storedAt: timestamp("stored_at", { withTimezone: true, mode: "date" }),
    supersededAt: timestamp("superseded_at", {
      withTimezone: true,
      mode: "date",
    }),
  },
  (table) => [
    uniqueIndex("project_document_versions_number_uidx").on(
      table.documentId,
      table.versionNumber,
    ),
    uniqueIndex("project_document_versions_upload_uidx").on(table.uploadId),
    uniqueIndex("project_document_versions_object_key_uidx").on(table.objectKey),
    unique("project_document_versions_id_document_project_unique").on(
      table.id,
      table.documentId,
      table.projectId,
    ),
    uniqueIndex("project_document_versions_one_current_uidx")
      .on(table.documentId)
      .where(sql`${table.isCurrent} = true`),
    index("project_document_versions_project_idx").on(
      table.projectId,
      table.documentId,
    ),
    index("project_document_versions_storage_idx").on(
      table.storageStatus,
      table.createdAt,
    ),
    foreignKey({
      name: "project_document_versions_document_project_fk",
      columns: [table.documentId, table.projectId],
      foreignColumns: [projectDocument.id, projectDocument.projectId],
    }).onDelete("restrict"),
    check(
      "project_document_versions_positive_number_check",
      sql`${table.versionNumber} > 0`,
    ),
    check(
      "project_document_versions_positive_size_check",
      sql`${table.sizeBytes} > 0`,
    ),
    check(
      "project_document_versions_sha256_check",
      sql`${table.sha256} ~ '^[0-9a-f]{64}$'`,
    ),
    check(
      "project_document_versions_current_stored_check",
      sql`${table.isCurrent} = false or ${table.storageStatus} = 'stored'`,
    ),
    check(
      "project_document_versions_stored_metadata_check",
      sql`${table.storageStatus} <> 'stored' or (
        ${table.storageEtag} is not null
        and length(btrim(${table.storageEtag})) > 0
        and ${table.storedAt} is not null
        and ${table.failureCode} is null
      )`,
    ),
    check(
      "project_document_versions_pending_state_check",
      sql`${table.storageStatus} <> 'pending' or (
        ${table.isCurrent} = false
        and ${table.storageEtag} is null
        and ${table.storedAt} is null
        and ${table.failureCode} is null
      )`,
    ),
    check(
      "project_document_versions_failure_state_check",
      sql`${table.storageStatus} not in ('failed', 'quarantined') or (
        ${table.isCurrent} = false
        and ${table.failureCode} is not null
        and length(btrim(${table.failureCode})) > 0
      )`,
    ),
    check(
      "project_document_versions_failure_code_scope_check",
      sql`${table.failureCode} is null or ${table.storageStatus} in ('failed', 'quarantined')`,
    ),
    check(
      "project_document_versions_deleted_not_current_check",
      sql`${table.storageStatus} <> 'deleted' or ${table.isCurrent} = false`,
    ),
  ],
);

export type ProjectDocumentRecord = typeof projectDocument.$inferSelect;
export type NewProjectDocumentRecord = typeof projectDocument.$inferInsert;
export type ProjectDocumentVersionRecord =
  typeof projectDocumentVersion.$inferSelect;
export type NewProjectDocumentVersionRecord =
  typeof projectDocumentVersion.$inferInsert;
